name: Go Test

on:
  push:
    branches: [trunk]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install protoc-gen-go and protoc-gen-go-grpc
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        env:
          PATH: ${{ env.PATH }}:${{ runner.temp }}/go/bin

      - name: Add go bin to PATH
        run: echo "${HOME}/go/bin" >> $GITHUB_PATH

      - name: Generate proto files
        run: make

      - name: Run Tests
        run: go test '-coverprofile=coverage.txt' './...'

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: shynur/chaindb
